name: market_app_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.5.2
  hive: ^2.2.3
  fluttertoast: ^8.2.8
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  hive_generator: ^2.0.0

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icon/



